web:
  restart: always
  image: dockerrepo.eionet.europa.eu:5000/helpadmin:latest
  ports:
    - "4480:8080"
    - "4409:8009"
  volumes:
    - /var/local/helpadmin:/var/local/helpadmin:ro
    - /etc/localtime:/etc/localtime:ro # Share timezone data with host
  environment:
    - HELPADMIN_CONF=/var/local/helpadmin/helpadmin.properties
    - CATALINA_OPTS=-Djava.security.egd=file:/dev/./urandom
  hostname: helpadmin
  mem_limit: 300M
